name: Daily Telegram Image Sender

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-image:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Create directories
      run: mkdir -p downloaded_images
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install telethon replicate requests
        
    - name: Run script
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        TELEGRAM_SESSION_1: ${{ secrets.TELEGRAM_SESSION_1 }}
        TELEGRAM_SESSION_2: ${{ secrets.TELEGRAM_SESSION_2 }}
      run: |
        echo "Checking environment variables (masked)..."
        if [ -n "$API_ID" ]; then echo "API_ID is set"; else echo "API_ID is missing"; fi
        if [ -n "$API_HASH" ]; then echo "API_HASH is set"; else echo "API_HASH is missing"; fi
        python telegram-user-account-script.py 